// Generated by tools/build_assets.py - material array layer ids.
#pragma once
namespace gtabr {
namespace mat {
constexpr int asphalt = 0;
constexpr int asphalt_cracked = 1;
constexpr int sidewalk = 2;
constexpr int pedra_port = 3;
constexpr int grass = 4;
constexpr int dirt = 5;
constexpr int tile_floor = 6;
constexpr int garage_floor = 7;
constexpr int house_yellow = 8;
constexpr int house_blue = 9;
constexpr int house_brick = 10;
constexpr int house_modern = 11;
constexpr int apt_beige = 12;
constexpr int apt_green = 13;
constexpr int sobrado_pink = 14;
constexpr int apt_bands = 15;
constexpr int shop_posto = 16;
constexpr int shop_mercado = 17;
constexpr int shop_oficina = 18;
constexpr int roof_tile = 19;
constexpr int roof_fiber = 20;
constexpr int roof_laje = 21;
constexpr int roof_metal = 22;
constexpr int wall_paint = 23;
constexpr int concrete = 24;
constexpr int wall_dark = 25;
constexpr int white = 26;
constexpr int shelf = 27;
constexpr int wood = 28;
constexpr int metal = 29;
constexpr int reserved0 = 30;
constexpr int reserved1 = 31;
constexpr int kCount = 32;
}  // namespace mat
}  // namespace gtabr
